#Levels drawn here
# W means wall, E means exit

levels = [[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W", 
    "WW                               WW",
    "WWW                             WWW",
    "WPP                             PPW",
    "W                                EW",
    "W                                 W",
    "WWW                             WWW",
    "WWP                             PWW",
    "WP                               PW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPPPPPPPPPPPPPPPPPPPPPPPPWWWWW",
    "W                              WWWW",
    "W                              PWWW",
    "W                               PWW",
    "W                                PW", 
    "WW                               WW",
    "WWW                             WWW",
    "WPP                         N   PPW",
    "W                                EW",
    "W                                 W",
    "WWW                         N   WWW",
    "WWP                             PWW",
    "WP                               PW",
    "W                                 W",
    "WW                                W",
    "WWW                               W",
    "WWWW                              W",
    "WWWWW                             W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPW",
    "W  N                              W",
    "W                                 W",
    "W                                 W",
    "W                                 W", 
    "WW                               WW",
    "WWW                             WWW",
    "WPP            WWWWWW           PPW",
    "W              WWWWWW   N        EW",
    "W              PPPPPP             W",
    "WWW                             WWW",
    "WWP                             PWW",
    "WP                               PW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W  N                              W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWPPPPPPPPPPPPPPPWWWWW",
    "WWWWWWWWWWWWWWW               WWWWW",
    "WWWWWWWWWWWWWWW          N    WWWWW",
    "WWWWWWWWWWWWWWW               WWWWW", 
    "WWWWWWWWWWWWWWW    WWWWWWWW   WWWWW",
    "WWWWWWWWWWWWWWW    WWWWWWWW   WWWWW",
    "WPPPPPPPWWWWWWW  N WWWWWWWW   PPPPW",
    "W       WWWWWWW    WWWWWWWW      EW",
    "W       WWWWWWW    WWWWWWWW       W",
    "WWWW    WWWWWWW    WWWWWWWWWWWWWWWW",
    "WWWW    WWWWWWW    WWWWWWWWWWWWWWWW",
    "WWWW    WWWWWWW    WWWWWWWWWWWWWWWW",
    "WWWW    PPPPPPP    WWWWWWWWWWWWWWWW",
    "WWWW               WWWWWWWWWWWWWWWW",
    "WWWW          N    WWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPWPPPPWPPPPWPPPPWPPPPWPPPPPPW",
    "W      W    W    W    W    W      W",
    "W      P    P    P    P    P      W",
    "W                                 W",
    "W                                 W", 
    "WW     W    W    W    W    W     WW",
    "WWW    P    P    P    P    P    WWW",
    "WPP                          N  PPW",
    "W                                EW",
    "W                                 W",
    "WWW                          N  WWW",
    "WWP    W    W    W    W    W    PWW",
    "WP     P    P    P    P    P     PW",
    "W                                 W",
    "W                                 W",
    "W      W    W    W    W    W      W",
    "W      P    P    P    P    P      W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPPPPPPPPPPPPPPPPPPPPPPPPWPPPW",
    "W                             W W W",
    "W                          N  W P W",
    "W                             WWWWW",
    "W                             PPPPW", 
    "WW                               WW",
    "WWW           WWWWWW            WWW",
    "WPP           WPPPPW   N        PPW",
    "W             W WW W             EW",
    "W             W WW W              W",
    "WWW           W PP W   N        WWW",
    "WWP           WWWWWW            PWW",
    "WP            PPPPPP             PW",
    "W                                 W",
    "WWWWW                             W",
    "WPPPW                             W",
    "W W W                      N      W",
    "W P W                             W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWPPPPPPPPPPPPPPPPPPPPPPPPPPPW",
    "WWWWWWW   WWWWWWWWWWWWWWWWWWWWW   W",
    "WWWWWWW   WWPPPPPPPPPPPWWWWWWWW N W",
    "WPPPPPP   PP           WWWWWWWW   W",
    "W   N                  WWWWWWWP   W", 
    "WWWWWWWWWWWW  WWWWWWW  WWWWWWW   WW",
    "WWWWWWWWWWWW  WPPWWWW  PPPPPPP  WWW",
    "WPPPPPPPPPPP  P  WWWW           PPW",
    "W                WWWW  N         EW",
    "W                WWWW    WW       W",
    "WWWWWWWW  WWWWW  WWWW    WW     WWW",
    "WWWWWWWW  WWWWW  WWWWWWWWWW   WWWWW",
    "WPWWWWWW  WWWWW  PPPPPPPPPP   WWWWW",
    "W WWWWWW  WWWWW               WWWWW",
    "W WWWWWW  WWWWW               WWWWW",
    "W WWWWWWWWWWWWW  WWWWWWWWWWWWWWWWWW",
    "W PPPPPPPPPPPPP  PPPPPPPPPPPPPPPPPW",
    "W      N                     N    W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWPPPPPPPPPPPPPPWWW",
    "WWWWWWWWWWWWWWWWWW              WWW",
    "WWWWWWWWWWWWWWWWWW  WWWWWWWWW   WWW",
    "WWWWWWWWWWWWWWWWWW  WWWWWWWWW   WWW", 
    "WWWWWWWWWWWWWWWWWW  WWWWWWWWW   WWW",
    "WWWWWWWWWWWWWWWWWW  WWWWWWWWW   WWW",
    "WPPPPWWPPPPPPPPPPP  PPPPPPPPW N PPW",
    "W    WW  N               N  W    EW",
    "W    WW                     W     W",
    "WWW  WW  N               N  WWWWWWW",
    "WWW  WWWWWWWWWWWW  WWWWWWWWWWWWWWWW",
    "WWW  WWWWWWWWWWWW  WWWWWWWWWWWWWWWW",
    "WWW  WWWWWWWWWWWW  WWWWWWWWWWWWWWWW",
    "WWW  PPPPPPPPPPPP  WWWWWWWWWWWWWWWW",
    "WWW                WWWWWWWWWWWWWWWW",
    "WWW                WWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPPPPPPPPPWWWWWWPPPPPPPPPPPPPW",
    "W              PPWWPP             W",
    "W          W     PP     W         W",
    "W          P            P         W",
    "W                                 W", 
    "WW     N                   N     WW",
    "WWW                             WWW",
    "WPP                             PPW",
    "W                                EW",
    "W                                 W",
    "WWW                             WWW",
    "WWP                             PWW",
    "WP                               PW",
    "W                                 W",
    "W      N                   N      W",
    "W                                 W",
    "W          W    W  W    W         W",
    "W          P   WWBBWW   P         W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPW",
    "W                   W             W",
    "W   W        N      P             W",
    "W   P                       W     W",
    "W        W                  P     W", 
    "WW       P                       WW",
    "WWW                             WWW",
    "WPP                      W      PPW",
    "W                        P       EW",
    "W              W                  W",
    "WWW            P                WWW",
    "WWP                   W         PWW",
    "WP     W              P          PW",
    "W      P                          W",
    "W            W                    W",
    "W            P        N           W",
    "W   N                        W    W",
    "W                            P    W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
    
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPW",
    "W                                 W",
    "W       WWWW      N     WWWW      W",
    "W       PPPP            PPPP      W",
    "W                                 W", 
    "WWWWWWW     WWWW    WWWW    WWWWWWW",
    "WWWPPPP     PPPP    PPPP    PPPPWWW",
    "WPP                             PPW",
    "W                                EW",
    "W                                 W",
    "WWW                             WWW",
    "WWWWWWW     WWWW    WWWW    WWWWWWW",
    "WPPPPPP     PPPP    PPPP    PPPPPPW",
    "W                                 W",
    "W                                 W",
    "W      WWWWW            WWWW      W",
    "W N    PPPPP            PPPP    N W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"

],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPWWWWWWWWWWWWWWPPPPWWWWWWWWWWWWPPW",
    "W PWWWWWWWWWWWWW    WWWWWWWWWWWP  W",
    "W  PWWWWWWWWWWWW NN WWWWWWWWWWP   W",
    "W   PWWWWWWWWWWW    WWWWWWWWWP    W",
    "W    PWWWWWWWWWW    WWWWWWWWP     W", 
    "WW    PPPPPPPPPP    PPPPPPPP     WW",
    "WWW                             WWW",
    "WPP                             PPW",
    "W                                EW",
    "W                                 W",
    "WWW                             WWW",
    "WWP                             PWW",
    "WP     WWWWWWWWW    WWWWWWWWW    PW",
    "W     WWWWWWWWWW    WWWWWWWWWW    W",
    "W    WWWWWWWWWWW    WWWWWWWWWWW   W",
    "W   WWWWWWWWWWWW NN WWWWWWWWWWWW  W",
    "W WWWWWWWWWWWWWW    WWWWWWWWWWWWW W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W", 
    "WW                W              WW",
    "WWW        W      W      W      WWW",
    "WPP        W      W      W      PPW",
    "W          W  N   W   N  W       EW",
    "W          W      W      W        W",
    "WWW        W      W      W      WWW",
    "WWP        P      W      P      PWW",
    "WP                P              PW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                 N               W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPW",
    "W                             N   W",
    "W                                 W",
    "W                                 W",
    "W                             N   W", 
    "WW                               WW",
    "WWW           WWWWWWW           WWW",
    "WPP           WWWWWWW         N PPW",
    "W           WWWWWWWWWWW          EW",
    "W           PPWWWWWWWPP           W",
    "WWW           WWWWWWW         N WWW",
    "WWP           PPPPPPP           PWW",
    "WP                               PW",
    "W                             N   W",
    "W                                 W",
    "W                                 W",
    "W                             N   W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPPPPPPPPPWWPPWWPPPPPPPPPPPPPW",
    "W              WP  PW    N        W",
    "W             WP    PW            W",
    "W             P      P            W",
    "W                 N               W", 
    "WW            W      W           WW",
    "WWW           PW    WP          WWW",
    "WPP            PW  WP           PPW",
    "W               W  W             EW",
    "W               W  W              W",
    "WWW            WP  PW           WWW",
    "WWP           WP    PW          PWW",
    "WP            P      P           PW",
    "W                N                W",
    "W             W      W            W",
    "W             PW    WP            W",
    "W              PW  WP    N        W",
    "W               WWWW              W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWPPPWWWWWWWWWWWWWWWWWWWWWWWPPPWWW",
    "WWW N PWWWWWWWWWWWWWWWWWWWWWP   WWW",
    "WWWW   PWWWWWWWWWWWWWWWWWWWP   WWWW",
    "WWWWW   PWWWWWWWWWWWWWWWWWP   WWWWW",
    "WWWWWW   PWWWWWWWWWWWWWWWP   WWWWWW", 
    "WWWWWWW   PWWWWWWWWWWWWWP   WWWWWWW",
    "WWWWWWWW   PWWWWWWWWWWWP   WWWWWWWW",
    "WPPPPPPP   PPPPPPPPPPP     PPPPPPPP",
    "W                           N    EW",
    "W                           N     W",
    "WWWWWWWWP   WWWWWWWWWWW   PWWWWWWWW",
    "WWWWWWWP   WWWWWWWWWWWWW   PWWWWWWW",
    "WWWWWWP   WWWWWWWWWWWWWWW   PWWWWWW",
    "WWWWWP   WWWWWWWWWWWWWWWWW   PWWWWW",
    "WWWWP   WWWWWWWWWWWWWWWWWWW   PWWWW",
    "WWWP   WWWWWWWWWWWWWWWWWWWWW   PWWW",
    "WWP N WWWWWWWWWWWWWWWWWWWWWWW   PWW",
    "WW   WWWWWWWWWWWWWWWWWWWWWWWWW   WW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPW",
    "W                N                W",
    "W   N       WWWW   WWWW       N   W",
    "W         WWPPPP   PPPPWW         W",
    "W       WWPP           PPWW       W", 
    "W     WWPP               PPWW    WW",
    "WWWWWWPP                   PWWWWWWW",
    "WPPPPP                      PPPPPPW",
    "W                                EW",
    "W                                 W",
    "WWWWWW                       WWWWWW",
    "WWPPPPWW                   WWPPPPWW",
    "WP    PPWW               WWPP    PW",
    "W       PPWW           WWPP       W",
    "W         PPWW       WWPP         W",
    "W           PPWW   WWPP           W",
    "W   N         PP   PP         N   W",
    "W                N                W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]]
