#Levels drawn here
# W means wall, E means exit

levels = [[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W", 
    "W                                 W",
    "WW                               WW",
    "WWW                             WWW",
    "W                                EW",
    "W                                 W",
    "WWW                             WWW",
    "WW                               WW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                             WWWWW",
    "W                              WWWW",
    "W                               WWW",
    "W                                WW",
    "W                                 W", 
    "W                                 W",
    "WW                               WW",
    "WWW                             WWW",
    "W                                EW",
    "W                                 W",
    "WWW                             WWW",
    "WW                               WW",
    "W                                 W",
    "W                                 W",
    "WW                                W",
    "WWW                               W",
    "WWWW                              W",
    "WWWWW                             W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W", 
    "W                                 W",
    "WW                               WW",
    "WWW            BBBBBB           WWW",
    "W             BBBBBBBB           EW",
    "W              BBBBBB             W",
    "WWW                             WWW",
    "WW                               WW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W             WWWWWWWWWWWWWWWWW   W",
    "W             W               W   W",
    "W             W               W   W",
    "W             W               W   W", 
    "W             W    WWWWWWWW   W   W",
    "WW            W    W      W   W  WW",
    "WWWWWWWWW     W    W      W   WWWWW",
    "W       W     W    W      W      EW",
    "W       W     W    W      W       W",
    "WWWW    W     W    W      WWWWWWWWW",
    "WW W    W     W    W             WW",
    "W  W    W     W    W              W",
    "W  W    WWWWWWW    W              W",
    "W  W               W              W",
    "W  W               W              W",
    "W  WWWWWWWWWWWWWWWWW              W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W      W    W    W    W    W      W",
    "W                                 W",
    "W                                 W",
    "W      W    W    W    W    W      W", 
    "W                                 W",
    "WW                               WW",
    "WWW    W    W    W    W    W    WWW",
    "W                                EW",
    "W                                 W",
    "WWW    W    W    W    W    W    WWW",
    "WW                               WW",
    "W                                 W",
    "W      W    W    W    W    W      W",
    "W                                 W",
    "W                                 W",
    "W      W    W    W    W    W      W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]]