#Levels drawn here
# W means wall, E means exit

levels = [[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W", 
    "W                                 W",
    "WW                               WW",
    "WWW                        N    WWW",
    "W                   N            EW",
    "W                                 W",
    "WWW                        N    WWW",
    "WW                               WW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                             WWWWW",
    "W                              WWWW",
    "W                               WWW",
    "W                                WW",
    "W                                 W", 
    "W                                 W",
    "WW                               WW",
    "WWW                             WWW",
    "W                                EW",
    "W                                 W",
    "WWW                             WWW",
    "WW                               WW",
    "W                                 W",
    "W                                 W",
    "WW                                W",
    "WWW                               W",
    "WWWW                              W",
    "WWWWW                             W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W", 
    "W                                 W",
    "WW                               WW",
    "WWW            BBBBBB           WWW",
    "W              BBBBBB            EW",
    "W              BBBBBB             W",
    "WWW                             WWW",
    "WW                               WW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWW               WWWWW",
    "WWWWWWWWWWWWWWW               WWWWW",
    "WWWWWWWWWWWWWWW               WWWWW", 
    "WWWWWWWWWWWWWWW    WWWWWWWW   WWWWW",
    "WWWWWWWWWWWWWWW    WWWWWWWW   WWWWW",
    "WWWWWWWWWWWWWWW    WWWWWWWW   WWWWW",
    "W       WWWWWWW    WWWWWWWW      EW",
    "W       WWWWWWW    WWWWWWWW       W",
    "WWWW    WWWWWWW    WWWWWWWWWWWWWWWW",
    "WWWW    WWWWWWW    WWWWWWWWWWWWWWWW",
    "WWWW    WWWWWWW    WWWWWWWWWWWWWWWW",
    "WWWW    WWWWWWW    WWWWWWWWWWWWWWWW",
    "WWWW               WWWWWWWWWWWWWWWW",
    "WWWW               WWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W      W    W    W    W    W      W",
    "W                                 W",
    "W                                 W",
    "W      W    W    W    W    W      W", 
    "W                                 W",
    "WW                               WW",
    "WWW    W    W    W    W    W    WWW",
    "W                                EW",
    "W                                 W",
    "WWW    W    W    W    W    W    WWW",
    "WW                               WW",
    "W                                 W",
    "W      W    W    W    W    W      W",
    "W                                 W",
    "W                                 W",
    "W      W    W    W    W    W      W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                             W   W",
    "W                             W W W",
    "W                             W   W",
    "W                             WWWWW",
    "W                                 W", 
    "W                                 W",
    "WW            WWWWWW             WW",
    "WWW           W    W            WWW",
    "W             W WW W             EW",
    "W             W WW W              W",
    "WWW           W    W            WWW",
    "WW            WWWWWW             WW",
    "W                                 W",
    "W                                 W",
    "WWWWW                             W",
    "W   W                             W",
    "W W W                             W",
    "W   W                             W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WBBBBBBB                          W",
    "WBBBBBBB  BBBBBBBBBBBBBBBBBBBBB   W",
    "WBBBBBBB  BBBBBBBBBBBBBBBBBBBBB   W",
    "WBBBBBBB  BB           BBBBBBBB   W",
    "W         BB           BBBBBBBB   W", 
    "WBBBBBBBBBBB  BBBBBBB  BBBBBBBB   W",
    "WWBBBBBBBBBB  B  BBBB  BBBBBBBB  WW",
    "WWWBBBBBBBBB  B  BBBB           WWW",
    "W                BBBB            EW",
    "W                BBBB    BB       W",
    "WWWBBBBB  BBBBB  BBBB    BB     WWW",
    "WWBBBBBB  BBBBB  BBBBBBBBBBB  BBBWW",
    "W BBBBBB  BBBBB  BBBBBBBBBBB  BBBBW",
    "W BBBBBB  BBBBB               BBBBW",
    "W BBBBBB  BBBBB               BBBBW",
    "W BBBBBBBBBBBBB  BBBBBBBBBBBBBBB  W",
    "W BBBBBBBBBBBBB  BBBBBBBBBBBBBBB  W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBW",
    "WBBBBBBBBBBBBBBBB               BBW",
    "WBBBBBBBBBBBBBBBB               BBW",
    "WBBBBBBBBBBBBBBBB  BBBBBBBBBBB  BBW",
    "WBBBBBBBBBBBBBBBB  BBBBBBBBBBB  BBW", 
    "WBBBBBBBBBBBBBBBB  BBBBBBBBBBB  BBW",
    "WWBBBBBBBBBBBBBBB  BBBBBBBBBBB  BWW",
    "WWWBBBB                     BB  WWW",
    "W    BB                     BB   EW",
    "W    BB                     BB    W",
    "WWW  BB                     BBBBWWW",
    "WWB  BBBBBBBBBBBB  BBBBBBBBBBBBBBWW",
    "WBB  BBBBBBBBBBBB  BBBBBBBBBBBBBBBW",
    "WBB  BBBBBBBBBBBB  BBBBBBBBBBBBBBBW",
    "WBB  BBBBBBBBBBBB  BBBBBBBBBBBBBBBW",
    "WBB                BBBBBBBBBBBBBBBW",
    "WBB                BBBBBBBBBBBBBBBW",
    "WBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W              WWBBWW             W",
    "W               W  W              W",
    "W          W            W         W",
    "W                                 W",
    "W                                 W", 
    "W                                 W",
    "WW                               WW",
    "WWW                             WWW",
    "W                                EW",
    "W                                 W",
    "WWW                             WWW",
    "WW                               WW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W          W    W  W    W         W",
    "W              WWBBWW             W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W                   W             W",
    "W   W                             W",
    "W                           W     W",
    "W        W                        W", 
    "W                                 W",
    "WW                               WW",
    "WWW                      W      WWW",
    "W                                EW",
    "W              W                  W",
    "WWW                             WWW",
    "WW                    W          WW",
    "W      W                          W",
    "W                                 W",
    "W            W                    W",
    "W                                 W",
    "W                            W    W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
    
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W                                 W",
    "W       WWWW            WWWW      W",
    "W                                 W",
    "W                                 W", 
    "W                                 W",
    "WWWWWWW     WWWW    WWWW    WWWWWWW",
    "WWW                             WWW",
    "W                                EW",
    "W                                 W",
    "WWW                             WWW",
    "WWWWWWW     WWWW    WWWW    WWWWWWW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W      WWWWW            WWWW      W",
    "W                                 W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"

],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W WWWWWWWWWWWWWW    WWWWWWWWWWWW  W",
    "W  WWWWWWWWWWWWW    WWWWWWWWWWW   W",
    "W   WWWWWWWWWWWW    WWWWWWWWWW    W",
    "W    WWWWWWWWWWW    WWWWWWWWW     W", 
    "W     WWWWWWWWWW    WWWWWWWW      W",
    "WW                               WW",
    "WWW                             WWW",
    "W                                EW",
    "W                                 W",
    "WWW                             WWW",
    "WW                               WW",
    "W      WWWWWWWWW    WWWWWWWWW     W",
    "W     WWWWWWWWWW    WWWWWWWWWW    W",
    "W    WWWWWWWWWWW    WWWWWWWWWWW   W",
    "W   WWWWWWWWWWWW    WWWWWWWWWWWW  W",
    "W WWWWWWWWWWWWWW    WWWWWWWWWWWWW W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W", 
    "W                 W               W",
    "WW         W      W      W       WW",
    "WWW        W      W      W      WWW",
    "W          W      W      W       EW",
    "W          W      W      W        W",
    "WWW        W      W      W      WWW",
    "WW         W      W      W       WW",
    "W                 W               W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W", 
    "W                                 W",
    "WW            WWWWWWW            WW",
    "WWW           WWWWWWW           WWW",
    "W           WWWWWWWWWWW          EW",
    "W           WWWWWWWWWWW           W",
    "WWW           WWWWWWW           WWW",
    "WW            WWWWWWW            WW",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W               W  W              W",
    "W              W    W             W",
    "W             W      W            W",
    "W                                 W", 
    "W             W      W            W",
    "WW             W    W            WW",
    "WWW             W  W            WWW",
    "W                                EW",
    "W                                 W",
    "WWW             W  W            WWW",
    "WW             W    W            WW",
    "W             W      W            W",
    "W                                 W",
    "W             W      W            W",
    "W              W    W             W",
    "W               W  W              W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "WW   WWWWWWWWWWWWWWWWWWWWWWWWW   WW",
    "WWW   WWWWWWWWWWWWWWWWWWWWWWW   WWW",
    "WWWW   WWWWWWWWWWWWWWWWWWWWW   WWWW",
    "WWWWW   WWWWWWWWWWWWWWWWWWW   WWWWW",
    "WWWWWW   WWWWWWWWWWWWWWWWW   WWWWWW", 
    "WWWWWWW   WWWWWWWWWWWWWWW   WWWWWWW",
    "WWWWWWWW   WWWWWWWWWWWWW   WWWWWWWW",
    "WWWWWWWWW   WWWWWWWWWWW   WWWWWWWWW",
    "W                                EW",
    "W                                 W",
    "WWWWWWWWW   WWWWWWWWWWW   WWWWWWWWW",
    "WWWWWWWW   WWWWWWWWWWWWW   WWWWWWWW",
    "WWWWWWW   WWWWWWWWWWWWWWW   WWWWWWW",
    "WWWWWW   WWWWWWWWWWWWWWWWW   WWWWWW",
    "WWWWW   WWWWWWWWWWWWWWWWWWW   WWWWW",
    "WWWW   WWWWWWWWWWWWWWWWWWWWW   WWWW",
    "WWW   WWWWWWWWWWWWWWWWWWWWWWW   WWW",
    "WW   WWWWWWWWWWWWWWWWWWWWWWWWW   WW",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
],[
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W                                 W",
    "W             WW   WW             W",
    "W           WW       WW           W",
    "W         WW           WW         W",
    "W       WW               WW       W", 
    "W     WW                   WW     W",
    "WW  WW                       WW  WW",
    "WWWW                           WWWW",
    "W                                EW",
    "W                                 W",
    "WWWW                           WWWW",
    "WW  WW                       WW  WW",
    "W     WW                   WW     W",
    "W       WW               WW       W",
    "W         WW           WW         W",
    "W           WW       WW           W",
    "W             WW   WW             W",
    "W                                 W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]]
